const loader=document.getElementById('loader');const menuToggle=document.getElementById('menuToggle');const navLinks=document.getElementById('navLinks');const form=document.getElementById('reservationForm');const modal=document.getElementById('successModal');const modalClose=document.getElementById('modalClose');const modalDone=document.getElementById('modalDone');const lightbox=document.getElementById('lightbox');const lightboxImage=document.getElementById('lightboxImage');const lightboxClose=document.getElementById('lightboxClose');
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
window.addEventListener('load',()=>setTimeout(()=>loader.classList.add('hide'),reducedMotion?0:500));
const progress=document.createElement('div');progress.className='scroll-progress';progress.innerHTML='<span></span>';document.body.appendChild(progress);const progressBar=progress.firstElementChild;
function updateScrollUI(){const scrollable=document.documentElement.scrollHeight-window.innerHeight;const progressValue=scrollable>0?(window.scrollY/scrollable)*100:0;progressBar.style.width=`${progressValue}%`;if(!reducedMotion&&window.innerWidth>800){const heroImage=document.querySelector('.hero-image');if(heroImage)heroImage.style.setProperty('--hero-shift',`${Math.min(window.scrollY*.08,35)}px`)}}window.addEventListener('scroll',updateScrollUI,{passive:true});updateScrollUI();
menuToggle.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuToggle.setAttribute('aria-expanded',open);document.body.style.overflow=open?'hidden':''});
navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuToggle.setAttribute('aria-expanded','false');document.body.style.overflow=''}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const sectionLinks=[...navLinks.querySelectorAll('a[href^="#"]')].filter(a=>a.getAttribute('href')!=='#');const sections=sectionLinks.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){sectionLinks.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===`#${entry.target.id}`))}}),{rootMargin:'-35% 0px -55% 0px',threshold:0});sections.forEach(section=>sectionObserver.observe(section));
const filters=document.querySelectorAll('.filter');const cards=document.querySelectorAll('.menu-card');filters.forEach(filter=>filter.addEventListener('click',()=>{filters.forEach(f=>f.classList.remove('active'));filter.classList.add('active');const category=filter.dataset.filter;cards.forEach((card,index)=>{const show=category==='all'||card.dataset.category===category;card.classList.toggle('is-hidden',!show);if(show){card.style.animation='none';void card.offsetWidth;card.style.animation=`cardIn .45s ${index*.06}s both`}})}));
form.addEventListener('submit',e=>{e.preventDefault();const date=form.querySelector('input[type=date]');const selected=date.value?new Date(`${date.value}T00:00:00`):null;const todayStart=new Date();todayStart.setHours(0,0,0,0);if(selected&&selected<todayStart){date.setCustomValidity('Choose a future date.');date.reportValidity();date.setCustomValidity('');return}modal.classList.add('open');modal.setAttribute('aria-hidden','false');form.reset()});
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}modalClose.addEventListener('click',closeModal);modalDone.addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
const galleryMap={g1:'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1800&q=90',g2:'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1800&q=90',g3:'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1800&q=90',g4:'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1800&q=90'};document.querySelectorAll('.gallery-item').forEach(item=>item.addEventListener('click',()=>{lightboxImage.style.backgroundImage=`url('${galleryMap[item.dataset.image]}')`;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false')}));function closeLightbox(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true')}lightboxClose.addEventListener('click',closeLightbox);lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});
const quotes=[['Coffee is a small ritual that makes an ordinary day feel intentional.','Noiré guest'],['The best moments are rarely planned. They simply happen around a good table.','Noiré guest'],['Slow mornings, honest food, and coffee worth staying for.','Noiré guest']];let quoteIndex=0;const quoteText=document.querySelector('.quote p');const quoteAuthor=document.querySelector('.quote span');if(quoteText&&quoteAuthor&&!reducedMotion){setInterval(()=>{quoteText.classList.add('quote-changing');setTimeout(()=>{quoteIndex=(quoteIndex+1)%quotes.length;quoteText.textContent=`“${quotes[quoteIndex][0]}”`;quoteAuthor.textContent=quotes[quoteIndex][1];quoteText.classList.remove('quote-changing')},350)},5000)}
if(window.matchMedia('(pointer:fine)').matches&&!reducedMotion){const magneticItems=document.querySelectorAll('.button,.nav-cta,.under-link');magneticItems.forEach(el=>{el.classList.add('magnetic');el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();const x=(e.clientX-(r.left+r.width/2))*.12;const y=(e.clientY-(r.top+r.height/2))*.12;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('pointerleave',()=>{el.style.transform=''})})}
const dateInput=form.querySelector('input[type=date]');const today=new Date();dateInput.min=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeLightbox();navLinks.classList.remove('open');menuToggle.setAttribute('aria-expanded','false');document.body.style.overflow=''}});
